Importing the libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

Loading the dataset

In [ ]:
df = pd.read_csv('/content/customer_feedback_sentiment__unique.csv')

In [ ]:
df.head()

   Feedback_ID                         Customer_Feedback Sentiment
0            1             Product quality excellent hai  Positive
1            2           Mobile ka camera bahut acha hai  Positive
2            3             Service fast aur reliable thi  Positive
3            4  Customer support ne problem solve kar di  Positive
4            5                 Packaging kaafi achhi thi  Positive

splitting features and labels

In [ ]:
X = df["Customer_Feedback"]   # Text data (features) jo cheez model ko dii jaati h
y = df["Sentiment"]           # Labels jo model ko predict karna h simple language  feedback dekar model se sentiment nikalwana h

Train test slit

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Text Vectorization(model text nhi smjhti sirf numbers smjhti h islie hum tf-idf vectrizer use krte h) simply words ko number me convert krta h

In [ ]:
vectorizer = TfidfVectorizer(stop_words="english")

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

Model training - Naive bayes

In [ ]:
model = MultinomialNB()
model.fit(X_train_vec, y_train)  # model har word ka probability nikalata h

MultinomialNB()

Prediction and Accuracy

In [ ]:
y_pred = model.predict(X_test_vec)  # model test data kasentiment predict krta h

print("Accuracy:", accuracy_score(y_test, y_pred))   # accuracy ->> model kitne baar shi predict kar paaya
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.05555555555555555

Classification Report:

              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00         6
     Neutral       0.20      0.25      0.22         4
    Positive       0.00      0.00      0.00         8

    accuracy                           0.06        18
   macro avg       0.07      0.08      0.07        18
weighted avg       0.04      0.06      0.05        18

Predict a sentiment of new feedback

In [ ]:
new_feedback = ["Brand trust ke layak hai"]

new_vec = vectorizer.transform(new_feedback)
prediction = model.predict(new_vec)

print("Sentiment:", prediction[0])

Sentiment: Positive

In [ ]:
df.shape

(90, 3)

In [ ]:
df['Sentiment'].value_counts()

Sentiment
Positive    30
Negative    30
Neutral     30
Name: count, dtype: int64

In [ ]:
#Product quality excellent hai
new_feedback = ["Battery backup low"]

new_vec = vectorizer.transform(new_feedback)
prediction = model.predict(new_vec)

print("Feedback:", new_feedback[0])
print("Sentiment:", prediction[0])

Feedback: Battery backup low
Sentiment: Neutral